services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gamepay
      POSTGRES_PASSWORD: gamepay
      POSTGRES_DB: gamepay
    ports:
      - "5432:5432"
    volumes:
      - gamepay_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  gamepay_pg_data:













